### ISSUE TITLE
金融機関の住所変更

### ISSUE THREAD

**Issue by tsugehara** [shinonomekazan/kazanshiki#31]
- [x] みずほ銀行
- [x] 楽天銀行
- [x] BitFlyer
- [x] DCom

**Comment by tsugehara** [comment]
みずほ: 行く必要あり。登記簿、代表者の身分証明、届け出印。

BitFlyerとDComはMaiに任せるか。

**Comment by tsugehara** [comment]
楽天は郵送済

**Comment by tsugehara** [comment]
みずほオッケー。デビット確認漏れ。電話する

**Comment by tsugehara** [comment]
デビット確認済。問題なし

**Comment by homai2504** [comment]
DCOMは完了、bitflyerは登録済、承認待ち状態です。

**Comment by homai2504** [comment]
bitflyerも承認済みようです。

**Comment by tsugehara** [comment]
やったぜ。終わり
