### ISSUE TITLE
粗大ごみを捨てる

### ISSUE THREAD

**Issue by tsugehara** [shinonomekazan/kazanshiki#99]
電気を捨てる。

まずは何捨てるかの認識合わせから。

**Comment by tsugehara** [comment]
まず、以前使ったところを僕から連絡する

**Comment by tsugehara** [comment]
中央区の問い合わせ先。

https://www.city.chuo.lg.jp/kusei/faq/kurasi/gomi/jigyoushasodaigomi.html

区役所に電話して、おすすめ３件くらい教えてもらい、前回は都清掃にお願いしました。

http://www.miyacoseisou.co.jp/

**Comment by SakamotoAmi** [comment]
都清掃さんは問い合わせメールしたのですが返信なく、今日電話したら担当者が不在でメールが来ているのかの確認ができないと言われたのですが、どちらにせよ明日連絡くださるそうです。口頭で見積もりしてもらったら13500円以上はかかるとのことでした。
